/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaoDienApp;

/**
 *
 * @author Admin
 */
public class OfflineReaderFrame extends javax.swing.JFrame {

    /**
     * Creates new form OfflineReaderFrame
     */
    public OfflineReaderFrame() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        mail_Pn = new javax.swing.JPanel();
        from_Lb = new javax.swing.JLabel();
        from_Tf = new javax.swing.JTextField();
        to_Lb = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        to_Tf = new javax.swing.JTextField();
        date_Lb = new javax.swing.JLabel();
        date_Tf = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cc_Lb = new javax.swing.JLabel();
        cc_Tf = new javax.swing.JTextField();
        bcc_Tf = new javax.swing.JTextField();
        bcc_Lb = new javax.swing.JLabel();
        subject_Tf = new javax.swing.JTextField();
        subject_Lb = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        tabPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTextHtml = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainTextPlain = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 910));

        mail_Pn.setBackground(new java.awt.Color(161, 233, 237));
        mail_Pn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        from_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        from_Lb.setText("From");
        mail_Pn.add(from_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        from_Tf.setBackground(new java.awt.Color(161, 233, 237));
        from_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        from_Tf.setBorder(null);
        from_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_TfActionPerformed(evt);
            }
        });
        mail_Pn.add(from_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 320, 30));

        to_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        to_Lb.setText("To");
        mail_Pn.add(to_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 320, 10));

        to_Tf.setBackground(new java.awt.Color(161, 233, 237));
        to_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        to_Tf.setBorder(null);
        to_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_TfActionPerformed(evt);
            }
        });
        mail_Pn.add(to_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 730, 30));

        date_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        date_Lb.setText("Date");
        mail_Pn.add(date_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        date_Tf.setBackground(new java.awt.Color(161, 233, 237));
        date_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        date_Tf.setBorder(null);
        date_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_TfActionPerformed(evt);
            }
        });
        mail_Pn.add(date_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 300, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 300, 10));

        cc_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        cc_Lb.setText("Cc");
        mail_Pn.add(cc_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cc_Tf.setBackground(new java.awt.Color(161, 233, 237));
        cc_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        cc_Tf.setBorder(null);
        mail_Pn.add(cc_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 730, 30));

        bcc_Tf.setBackground(new java.awt.Color(161, 233, 237));
        bcc_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        bcc_Tf.setBorder(null);
        mail_Pn.add(bcc_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 730, 30));

        bcc_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        bcc_Lb.setText("Bcc");
        mail_Pn.add(bcc_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        subject_Tf.setBackground(new java.awt.Color(161, 233, 237));
        subject_Tf.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        subject_Tf.setBorder(null);
        subject_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_TfActionPerformed(evt);
            }
        });
        mail_Pn.add(subject_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 730, 30));

        subject_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        subject_Lb.setText("Subject");
        mail_Pn.add(subject_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 730, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 730, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 730, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        mail_Pn.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 732, 10));

        jScrollPane2.setViewportView(mainTextHtml);

        tabPane.addTab("Full", jScrollPane2);

        jScrollPane3.setViewportView(mainTextPlain);

        tabPane.addTab("Plain only", jScrollPane3);

        mail_Pn.add(tabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 870, 680));

        getContentPane().add(mail_Pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 870, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void from_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_TfActionPerformed

    private void to_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_TfActionPerformed

    private void date_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_TfActionPerformed

    private void subject_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_TfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(OfflineReaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(OfflineReaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(OfflineReaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(OfflineReaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new OfflineReaderFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bcc_Lb;
    private javax.swing.JTextField bcc_Tf;
    private javax.swing.JLabel cc_Lb;
    private javax.swing.JTextField cc_Tf;
    private javax.swing.JLabel date_Lb;
    private javax.swing.JTextField date_Tf;
    private javax.swing.JLabel from_Lb;
    private javax.swing.JTextField from_Tf;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel mail_Pn;
    private javax.swing.JEditorPane mainTextHtml;
    private javax.swing.JEditorPane mainTextPlain;
    private javax.swing.JLabel subject_Lb;
    private javax.swing.JTextField subject_Tf;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JLabel to_Lb;
    private javax.swing.JTextField to_Tf;
    // End of variables declaration//GEN-END:variables
}
